repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
        exclude: grammars
    -   id: check-merge-conflict
-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
        name: Check project styling
        exclude: grammars
        args:
        - --ignore=F403,F405
        - --max-line-length=160
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: Sort python imports (shows diff)
        exclude: grammars
        args: ["-c", "--diff"]
    -   id: isort
        name: Sort python imports (fixes files)
        exclude: grammars
