# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: cti-pattern-validator test harness
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    name: Python ${{ matrix.python-version }} Build
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install and update essential dependencies
      run: |
        pip install -U pip setuptools
        pip install tox-gh-actions
        pip install codecov
    - name: Test with Tox
      run: |
        tox
    - name: Upload coverage information to Codecov
      uses: codecov/codecov-action@v4.2.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false # optional (default = false)
        verbose: true # optional (default = false)
